services:
  mongodb:
    image: mongo:latest
    container_name: contact_recognition_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: contact_recognition
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: contact_recognition_backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      MONGODB_URL: mongodb://admin:adminpassword@contact_recognition_mongodb:27017
    ports:
      - "9211:8000"
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://83.229.86.141:9211
    container_name: contact_recognition_frontend
    restart: always
    ports:
      - "9210:80"

volumes:
  mongodb_data:
    driver: local
