repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        description: Trims trailing whitespace.
      - id: end-of-file-fixer
        description: Ensures that a file is either empty or ends with one newline.
      - id: check-yaml
        description: Attempts to load all yaml files to verify syntax.
      - id: check-added-large-files
        description: Prevents giant files from being committed.
        args: ['--maxkb=500']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      # Run the Ruff linter and apply automatic fixes (--fix)
      - id: ruff
        name: Ruff Linter
        description: Extremely fast Python linter checking coding standards and applying automatic fixes.
        args: [ --fix, --exit-non-zero-on-fix ]

      # Run the Ruff formatter to auto-format files
      - id: ruff-format
        name: Ruff Formatter
        description: Auto-format Python files to adhere to strict formatting standards.
